#!/bin/sh

#Wait for be sure network is up and add a safety
host=192.168.1.1
sleep 70

while true; do
loss=`ping -c 10 -q $host | grep -oP '\d+(?=% packet loss)'`

if [ $loss -eq '100' ]; then
    NOW=$(date +"%m-%d-%Y")
    echo "$NOW - reboot" >> /tmp/reboot.txt
    reboot
    exit 1
else
    NOW=$(date +"%m-%d-%Y")
    echo "$NOW - ok" >> /tmp/reboot.txt
fi
sleep 5

done
