#!/bin/sh

#Wait for be sure network is up and add a safety
sleep 70

while true; do
ping -c1 192.168.1.1 > /dev/null 2>&1

if [ $? -eq 0 ]; then
    NOW=$(date +"%m-%d-%Y")
    echo "$NOW - ok" >> /tmp/reboot.txt
else
    NOW=$(date +"%m-%d-%Y")
    echo "$NOW - reboot" >> /tmp/reboot.txt
    reboot
    exit 1
fi
sleep 10

done
